language: node_js
node_js:
 - "stable"
before_install:
 - export CXX="g++-6" CC="gcc-6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libbsd-dev
sudo: false
